services:
  - type: web
    name: portfolio-site
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
